### ISSUE TITLE
Update to use Unicode 7.0

### ISSUE THREAD

**Issue by bnjmnt4n** [devongovett/grapheme-breaker#1]

**Comment by bnjmnt4n** [comment]
Ping? ;)

**Comment by devongovett** [comment]
Are there changes to any of the rules or categories in Unicode 7.0? I assume there are more character assignments but that can be updated by just updating this [script](https://github.com/devongovett/grapheme-breaker/blob/master/src/generate_data.coffee#L5). If you want to test if it is working, update this [test file](https://github.com/devongovett/grapheme-breaker/blob/master/test/GraphemeBreakTest.txt) to the unicode 7.0 version.  If there are rule changes, we'll need to update the code as well.
